// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reservation.Models;

namespace Reservation.Migrations
{
    [DbContext(typeof(ReservationContext))]
    partial class ReservationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Reservation.Models.FoodList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FoodType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("FoodList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FoodType = "Pizza"
                        },
                        new
                        {
                            Id = 2,
                            FoodType = "Sea Food"
                        },
                        new
                        {
                            Id = 3,
                            FoodType = "Fried Chicken"
                        });
                });

            modelBuilder.Entity("Reservation.Models.ReservationTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FoodTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PepoleNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReservationDate")
                        .HasColumnType("date");

                    b.Property<int?>("TableNo")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("ReservationTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PepoleNumber = 5,
                            ReservationDate = new DateTime(2021, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableNo = 12,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            PepoleNumber = 10,
                            ReservationDate = new DateTime(2021, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableNo = 15,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Reservation.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "george yanni",
                            Password = "2CE4B2E3EFCC473A6ED2D70B01C4D7E9",
                            Username = "georgey"
                        },
                        new
                        {
                            Id = 2,
                            Name = "helmy adam",
                            Password = "EED23196E62F8B98B6FD2EA881FEC77A",
                            Username = "helmya"
                        });
                });

            modelBuilder.Entity("Reservation.Models.ReservationTable", b =>
                {
                    b.HasOne("Reservation.Models.FoodList", "FoodType")
                        .WithMany("ReservationTables")
                        .HasForeignKey("FoodTypeId")
                        .HasConstraintName("FK_ReservationTable_FoodTypes");

                    b.HasOne("Reservation.Models.User", "User")
                        .WithMany("ReservationTables")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_ReservationTable_User");

                    b.Navigation("FoodType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reservation.Models.FoodList", b =>
                {
                    b.Navigation("ReservationTables");
                });

            modelBuilder.Entity("Reservation.Models.User", b =>
                {
                    b.Navigation("ReservationTables");
                });
#pragma warning restore 612, 618
        }
    }
}
